import { ResumeTemplate, Resume } from "./types/resume";

export const templates: Record<string, { name: string; description: string }> = {
  "classic-clear": {
    name: "Classic Clear",
    description: "Single column, black/white, serif fonts, traditional layout",
  },
  "modern-blue": {
    name: "Modern Blue",
    description: "Two-column left sidebar, blue accent, sans-serif",
  },
  "minimal-clean": {
    name: "Minimal Clean",
    description: "Single column, large whitespace, minimal borders",
  },
  "creative-side": {
    name: "Creative Side",
    description: "Two-column with colored left sidebar, bold header",
  },
  "corporate-pro": {
    name: "Corporate Pro",
    description: "Single column, dark header band, professional",
  },
  "tech-stack": {
    name: "Tech Stack",
    description: "Two-column right sidebar, monospace accents, for developers",
  },
  "elegant-serif": {
    name: "Elegant Serif",
    description: "Single column, elegant serif typography, subtle lines",
  },
  "bold-header": {
    name: "Bold Header",
    description: "Full-width colored header, clean body",
  },
  "minimal-slate": {
    name: "Minimal Slate",
    description: "Dark grey accents, compact layout, clean fonts",
  },
  "creative-orange": {
    name: "Creative Orange",
    description: "Bright orange accent, centered header layout",
  },
  "modern-emerald": {
    name: "Modern Emerald",
    description: "Left sidebar layout with rich emerald highlights",
  },
  "ats-standard": {
    name: "ATS Standard",
    description: "Plain black & white, high parsing rate, no columns",
  },
};

export const templateList: ResumeTemplate[] = [
  {
    id: "classic-clear",
    name: "Classic Clear",
    category: "classic",
    atsScore: 92,
    colors: {
      primary: "#111827",
      secondary: "#4B5563",
      text: "#1F2937",
      background: "#FFFFFF",
      accent: "#374151",
    },
    layout: "single-column",
    typography: {
      headingFont: "Playfair Display",
      bodyFont: "Merriweather",
      headingSize: 22,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "centered",
  },
  {
    id: "modern-blue",
    name: "Modern Blue",
    category: "modern",
    atsScore: 88,
    colors: {
      primary: "#1E3A8A",
      secondary: "#3B82F6",
      text: "#1F2937",
      background: "#FFFFFF",
      accent: "#EFF6FF",
    },
    layout: "two-column-left",
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      headingSize: 20,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "left-aligned",
  },
  {
    id: "minimal-clean",
    name: "Minimal Clean",
    category: "minimal",
    atsScore: 95,
    colors: {
      primary: "#000000",
      secondary: "#6B7280",
      text: "#374151",
      background: "#FFFFFF",
      accent: "#F3F4F6",
    },
    layout: "single-column",
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      headingSize: 18,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "left-aligned",
  },
  {
    id: "creative-side",
    name: "Creative Side",
    category: "creative",
    atsScore: 78,
    colors: {
      primary: "#3626A7",
      secondary: "#6366F1",
      text: "#1F2937",
      background: "#EEF2FF",
      accent: "#4F46E5",
    },
    layout: "two-column-left",
    typography: {
      headingFont: "Outfit",
      bodyFont: "Outfit",
      headingSize: 22,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "with-sidebar",
  },
  {
    id: "corporate-pro",
    name: "Corporate Pro",
    category: "classic",
    atsScore: 90,
    colors: {
      primary: "#0F172A",
      secondary: "#475569",
      text: "#334155",
      background: "#FFFFFF",
      accent: "#1E293B",
    },
    layout: "single-column",
    typography: {
      headingFont: "Roboto",
      bodyFont: "Roboto",
      headingSize: 20,
      bodySize: 10.5,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "left-aligned",
  },
  {
    id: "tech-stack",
    name: "Tech Stack",
    category: "modern",
    atsScore: 86,
    colors: {
      primary: "#059669",
      secondary: "#10B981",
      text: "#0F172A",
      background: "#FFFFFF",
      accent: "#ECFDF5",
    },
    layout: "two-column-right",
    typography: {
      headingFont: "JetBrains Mono",
      bodyFont: "Inter",
      headingSize: 19,
      bodySize: 9.5,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "left-aligned",
  },
  {
    id: "elegant-serif",
    name: "Elegant Serif",
    category: "classic",
    atsScore: 85,
    colors: {
      primary: "#78350F",
      secondary: "#B45309",
      text: "#451A03",
      background: "#FFFBEB",
      accent: "#FEF3C7",
    },
    layout: "single-column",
    typography: {
      headingFont: "Lora",
      bodyFont: "Lora",
      headingSize: 22,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "centered",
  },
  {
    id: "bold-header",
    name: "Bold Header",
    category: "creative",
    atsScore: 82,
    colors: {
      primary: "#BE185D",
      secondary: "#DB2777",
      text: "#1F2937",
      background: "#FFFFFF",
      accent: "#FCE7F3",
    },
    layout: "single-column",
    typography: {
      headingFont: "Plus Jakarta Sans",
      bodyFont: "Inter",
      headingSize: 24,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "centered",
  },
  {
    id: "minimal-slate",
    name: "Minimal Slate",
    category: "minimal",
    atsScore: 94,
    colors: {
      primary: "#374151",
      secondary: "#4B5563",
      text: "#1F2937",
      background: "#FAFAFA",
      accent: "#F3F4F6",
    },
    layout: "single-column",
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      headingSize: 19,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "left-aligned",
  },
  {
    id: "creative-orange",
    name: "Creative Orange",
    category: "creative",
    atsScore: 80,
    colors: {
      primary: "#EA580C",
      secondary: "#F97316",
      text: "#1C1917",
      background: "#FFFBF7",
      accent: "#FFEDD5",
    },
    layout: "single-column",
    typography: {
      headingFont: "Outfit",
      bodyFont: "Outfit",
      headingSize: 23,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "centered",
  },
  {
    id: "modern-emerald",
    name: "Modern Emerald",
    category: "modern",
    atsScore: 87,
    colors: {
      primary: "#065F46",
      secondary: "#047857",
      text: "#1F2937",
      background: "#FFFFFF",
      accent: "#ECFDF5",
    },
    layout: "two-column-left",
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      headingSize: 20,
      bodySize: 10,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "left-aligned",
  },
  {
    id: "ats-standard",
    name: "ATS Standard",
    category: "minimal",
    atsScore: 98,
    colors: {
      primary: "#000000",
      secondary: "#000000",
      text: "#000000",
      background: "#FFFFFF",
      accent: "#E5E7EB",
    },
    layout: "single-column",
    typography: {
      headingFont: "Roboto",
      bodyFont: "Roboto",
      headingSize: 18,
      bodySize: 10.5,
    },
    sectionOrder: ["summary", "experience", "education", "skills", "projects", "certifications", "languages"],
    headerStyle: "left-aligned",
  },
];

export const getDefaultResume = (templateId: string, title: string = "My Resume"): Partial<Resume> => {
  const tpl = templateList.find((t) => t.id === templateId) || templateList[0];

  return {
    name: title,
    templateId: tpl.id,
    design: {
      primaryColor: tpl.colors.primary,
      accentColor: tpl.colors.secondary,
      textColor: tpl.colors.text,
      backgroundColor: tpl.colors.background,
      headingFont: tpl.typography.headingFont,
      bodyFont: tpl.typography.bodyFont,
      fontSize: "md",
      pageMargin: "normal",
      sectionSpacing: "normal",
      layout: tpl.layout === "single-column" ? "single" : (tpl.layout === "two-column-left" ? "two-column-left" : "two-column-right"),
      headerStyle: tpl.headerStyle === "centered" ? "minimal" : (tpl.headerStyle === "with-sidebar" ? "sidebar" : "minimal"),
      showDividers: true,
    },
    content: {
      personalInfo: {
        name: "",
        email: "",
        phone: "",
        location: "",
        linkedin: "",
        website: "",
        photoURL: "",
      },
      summary: "",
      experience: [],
      education: [],
      skills: [],
      projects: [],
      certifications: [],
      languages: [],
      customSections: [],
    },
    sectionOrder: [
      "summary",
      "experience",
      "education",
      "skills",
      "projects",
      "certifications",
      "languages",
      "customSections"
    ],
  };
};
